create table Movie (
id INTEGER NOT NULL ,
title varchar(255) DEFAULT NULL,
year varchar(255) DEFAULT NULL,
language varchar(255) DEFAULT NULL,
rented BOOLEAN DEFAULT FALSE NOT NULL,
PRIMARY KEY(id));


create table RentalRecord (
id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY(START WITH 1, INCREMENT BY 1),
userName varchar(255) NOT NULL,
movieId INTEGER NOT NULL,
PRIMARY KEY(id));